packages:
  - "packages/**"
  - "app/**"

catalog:
  reflect-metadata: ^0.1.13
  electron: ^33.2.1
  tsyringe: ^4.10.0
  "@typescript/native-preview": 7.0.0-dev.20260325.1
  inversify: ^6.2.1
  "@mariozechner/pi-ai": ^0.73.1
  "@mariozechner/pi-agent-core": ^0.73.1
