export const OPEN_SETTING_WINDOW = 'OPEN_SETTING_WINDOW';

export const SET_THEME = 'SET_THEME';
export const THEME_LIGHT = 'SET_THEME_LIGHT';
export const THEME_DARK = 'SET_THEME_dark';
export const START_AI_STREAM = 'START_AI_STREAM';
export const CREATE_CHAT_SESSION = 'CREATE_CHAT_SESSION';
export const AI_STREAM = 'AI_STREAM';
export const AI_RENAME = 'AI_RENAME';
// AI 文件重命名（渲染进程页面版）
export const AI_RENAME_RECOMMEND = 'AI_RENAME_RECOMMEND';
export const AI_RENAME_APPLY = 'AI_RENAME_APPLY';
export const AI_IMPORT_TO_NOTION = 'AI_IMPORT_TO_NOTION';
export const PARSE_BILL_RESULT = 'PARSE_BILL_RESULT';
export const UPADTA_BILL = 'UPADTA_BILL';

// 上传账单三步流：AI 分类 + 上传
export const PARSE_BILL_FILE = 'PARSE_BILL_FILE';
export const AI_CLASSIFY_BILL = 'AI_CLASSIFY_BILL';
export const AI_CLASSIFY_DONE = 'AI_CLASSIFY_DONE';
export const UPLOAD_BILL_TO_NOTION = 'UPLOAD_BILL_TO_NOTION';
export const UPLOAD_BILL_PROGRESS = 'UPLOAD_BILL_PROGRESS';

// 账单月报
