export const ECHO = "ECHO";
export const START_OPENCODE = "START_OPENCODE";
export const INIT = "INIT";
export const INIT_PROGRESS = "INIT_PROGRESS";
export const INIT_WORKSPACE = "INIT_WORKSPACE";
export const INIT_OPENCODE_SERVICE = "INIT_OPENCODE_SERVICE";
export const SELECT_DIRECTORY = "SELECT_DIRECTORY";
