export const REGISTER_EVENT = "REGISTER_EVENT";
export const EVENT_BUS = "EVENT_BUS";
export const GET_APP_INFO = "GET_APP_INFO";
export const GET_PROVIDER_CATALOG = "GET_PROVIDER_CATALOG";
export const GET_CREDENTIAL = "GET_CREDENTIAL";
export const SET_CREDENTIAL = "SET_CREDENTIAL";
export const DELETE_CREDENTIAL = "DELETE_CREDENTIAL";
